name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run tests
        run: cargo test --workspace --exclude scrap_rt

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Clippy check
        run: cargo clippy --all-targets --workspace -- -D warnings

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Check formatting
        run: cargo fmt --all --check

  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@master
